events {}

http {
    upstream backend_nodes {
        server node1:5000;
        server node2:5000;
        server node3:5000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend_nodes;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
